### PR TITLE
Name Change: Issue #226

### PR DESCRIPTION
**Pull request by RohanJacob23**
Description
Name changed from sdks/web-sdk to sdks/web-ui-sdk #226

Related issues
Issue #226

### Checklist
- [x] I have read the [contribution guidelines](CONTRIBUTING.md) of this project
- [x] I have read the [style guidelines](STYLE_GUIDE.md) of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings and errors
- [x] New and existing tests pass locally with my changes

Note - I accidentally closed the previous PR. Sorry for the inconvenience.

### CODE REVIEW

**Comment by RohanJacob23** [comment]
### I am talking about these files:-

**`ballerine\websites\docs\src\styles\index.css`**
```css
.web-sdk-api__ul li {
  margin-block: 1rem;
  list-style: none;
  line-height: 1.5;
}

.web-sdk-api__ul li::before {
  content: '•';
  margin-inline-end: 0.5rem;
}

.web-sdk-api__ul code {
  font-weight: bold;
  color: #000;
}

.web-sdk-api__ul pre {
  margin-inline-start: 1rem;
}

.web-sdk-api__ul p {
  padding-inline-start: 1rem;
}
```
Note - I accidentally closed the previous PR. Sorry for the inconvenience.

**Comment by Omri-Levy** [comment]
> ### I am talking about these files:-
> **`ballerine\websites\docs\src\styles\index.css`**
> 
> ```css
> .web-sdk-api__ul li {
>   margin-block: 1rem;
>   list-style: none;
>   line-height: 1.5;
> }
> 
> .web-sdk-api__ul li::before {
>   content: '•';
>   margin-inline-end: 0.5rem;
> }
> 
> .web-sdk-api__ul code {
>   font-weight: bold;
>   color: #000;
> }
> 
> .web-sdk-api__ul pre {
>   margin-inline-start: 1rem;
> }
> 
> .web-sdk-api__ul p {
>   padding-inline-start: 1rem;
> }
> ```
> 
> Note - I accidentally closed the previous PR. Sorry for the inconvenience.

These classes are not in use, we can ignore them for now. 👍

**Comment by RohanJacob23** [comment]
Thank you @Omri-Levy for the response.

Could you please confirm if everything else in the pull request looks good to you?

**Comment by Omri-Levy** [comment]
> Thank you @Omri-Levy for the response.
> 
> Could you please confirm if everything else in the pull request looks good to you?

Just revert `CHANGELOG.md` and we're good to go! 🙌

**Comment by RohanJacob23** [comment]
@Omri-Levy, I have reverted the changes in `CHANGELOG.md`

**Review by Omri-Levy — CHANGES_REQUESTED** [review]
Thanks for the changes! Could you just resolve the conflicts? 😄

**Comment by RohanJacob23** [comment]
> Thanks for the changes! Could you just resolve the conflicts? 😄

Hi @Omri-Levy,

I realized that I forgot to sync my forked repo, which caused a merge conflict and prompted me to discard my previous changes. Should I create a new PR? Could you please guide me on how to proceed?

**Comment by Omri-Levy** [comment]
> > Thanks for the changes! Could you just resolve the conflicts? 😄
> 
> Hi @Omri-Levy,
> 
> I realized that I forgot to sync my forked repo, which caused a merge conflict and prompted me to discard my previous changes. Should I create a new PR? Could you please guide me on how to proceed?

Could you elaborate on what do you mean by discarded your changes?

**Comment by RohanJacob23** [comment]
I am seeing this message,
And sorry for any inconveniences

**Comment by Omri-Levy** [comment]
> 
> 
> I am seeing this message, And sorry for any inconveniences

Not at all! See if you can resolve the conflicts via your code editor. If that doesn't work, we can move this conversation to Slack. :slightly_smiling_face:

**Pull request closed without merging**
