### PR TITLE
Name change

### PR DESCRIPTION
**Pull request by RohanJacob23**
Description
Name changed from sdks/web-sdk to sdks/web-ui-sdk #226

Related issues
Issue #226

### Checklist
- [x] I have read the [contribution guidelines](CONTRIBUTING.md) of this project
- [x] I have read the [style guidelines](STYLE_GUIDE.md) of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings and errors
- [x] New and existing tests pass locally with my changes

### CODE REVIEW

**Comment by RohanJacob23** [comment]
Hello @Omri-Levy,

Can you please review my PR

**Comment by Omri-Levy** [comment]
> Hello @Omri-Levy,
> 
> Can you please review my PR

Will do as soon as I can.

**Comment by alonp99** [comment]
Thank you @RohanJacob23 

Can you resolve the conflicts so will be able to merge the PR?

**Comment by RohanJacob23** [comment]
> Thank you @RohanJacob23 
> 
> Can you resolve the conflicts so will be able to merge the PR?

Sorry for the late response,

I will fix it in one or two days.

**Pull request closed without merging**
