### PR TITLE
Error Handlings

### PR DESCRIPTION
**Pull request by SpekGit**
### Description
Elaborate on the subject, motivation, and context.

### Related issues
 * Provide a link to each related issue.

### Breaking changes
 * Describe the breaking changes that this pull request introduces.

### How these changes were tested
 * Describe the tests that you ran to verify your changes, including devices, operating systems, browsers and versions.

### Examples and references
 * Links, screenshots, and other resources related to this change.

### Checklist
- [+] I have read the [contribution guidelines](CONTRIBUTING.md) of this project
- [+] I have read the [style guidelines](STYLE_GUIDE.md) of this project
- [+] I have performed a self-review of my own code
- [+] I have commented my code, particularly in hard-to-understand areas
- [+] I have made corresponding changes to the documentation
- [+] My changes generate no new warnings and errors
- [+] New and existing tests pass locally with my changes

### CODE REVIEW

**Comment by alonp99** [comment]
Hey @SpekGit, thanks for contributing but it seems like all the recent PRs by you have the same content and it's creating some clutter in the PR queue - I would be happy to catch up in slack (you can find the link in the readme) and direct you to some tasks we need help with

**Comment by SpekGit** [comment]
That sounds great. I'd love to connect.

**Comment by SpekGit** [comment]
Sorry for not mentioning this yesterday but my Slack email is
***@***.*** and my profile name is david_oleksy.

**Comment by SpekGit** [comment]
Hello @alonp99, I just wanted to reach out and ask if you're still interested in adding me to the Slack channel.

**Comment by alonp99** [comment]
@SpekGit here is the slack link: https://join.slack.com/t/ballerine-oss/shared_invite/zt-1iu6otkok-OqBF3TrcpUmFd9oUjNs2iw

**Pull request closed without merging**
